# Generated by Django 6.0.7 on 2026-07-28 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('transactions', '0002_alter_transactions_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='expenses.expense'),
        ),
    ]
