# Generated by Django 6.0.7 on 2026-07-30 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
        ('transactions', '0003_transactions_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='savings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='savings.savings'),
        ),
    ]
