# Generated by Django 6.0.7 on 2026-08-02 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
        ('transactions', '0004_transactions_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='debts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='debts.debts'),
        ),
    ]
